refactor: Rewrite updateFilteredPolicies method
php-casbin/cake-permission pull request #11
Opened 2021-09-22 14:31 UTC by basakest

2021-09-23 04:46 UTC, hsluoyz commented
@techoner plz review

2021-09-23 15:45 UTC, techoner requested changes

2021-09-23 15:45 UTC, techoner commented on src/Adapter.php
> +                $removedRules[] = array_values($row);
@basakest For filtering rules, please refer to: https://github.com/php-casbin/dbal-adapter/blob/master/src/Adapter.php#L435

2021-09-23 15:45 UTC, techoner commented on src/Adapter.php
> +            $this->removePolicies($sec, $ptype, $removedRules);
Here again use `removePolicies` to delete one by one, which will affect performance .

2021-09-25 14:25 UTC, techoner requested changes

2021-09-25 14:25 UTC, techoner commented on src/Adapter.php
>          throw new CasbinException('not implemented');
@basakest Please implements it use `_removeFilteredPolicy()`.

2021-09-26 15:46 UTC, techoner approved these changes

2021-09-26 15:47 UTC, merged

2023-09-11 08:40 UTC, leeqvip commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on [GitHub release](https://github.com/php-casbin/cake-permission/releases/tag/v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-09-11 08:51 UTC, leeqvip commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on [GitHub release](https://github.com/php-casbin/cake-permission/releases/tag/v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: